name: CMake-Format

on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 5 * * *'

jobs:
  cmake_format:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Run CMake Lang Format Check
        run: |
          pip3 install cmakelang
          git init
          ./.run-cmake-format
          output=$(git diff)
          if [ -n "$output" ]; then exit 1; else exit 0; fi
